import { RetailerId, RetailerInfo } from "@/types";

/**
 * Central Retailer Registry
 * Single Source of Truth for retailer metadata, connection status, data source type, and styling.
 * Prevents hardcoding retailer information across individual UI components.
 */
export const RETAILER_REGISTRY: Record<RetailerId, RetailerInfo> = {
  amazon: {
    id: "amazon",
    name: "Amazon India",
    countryCode: "IN",
    currency: "INR",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "api",
    dataSource: "Official Product Advertising / Creators API",
    affiliateSupported: true,
    iconColorClass: "text-amber-400 border-amber-500/20 bg-amber-500/10",
  },
  flipkart: {
    id: "flipkart",
    name: "Flipkart",
    countryCode: "IN",
    currency: "INR",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "affiliate_feed",
    dataSource: "Official Flipkart Affiliate API Feed",
    affiliateSupported: true,
    iconColorClass: "text-blue-400 border-blue-500/20 bg-blue-500/10",
  },
  croma: {
    id: "croma",
    name: "Croma",
    countryCode: "IN",
    currency: "INR",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "merchant_feed",
    dataSource: "Croma Store Partner Feed",
    affiliateSupported: true,
    iconColorClass: "text-teal-400 border-teal-500/20 bg-teal-500/10",
  },
  "reliance-digital": {
    id: "reliance-digital",
    name: "Reliance Digital",
    countryCode: "IN",
    currency: "INR",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "merchant_feed",
    dataSource: "Reliance Digital Store Partner Feed",
    affiliateSupported: true,
    iconColorClass: "text-red-400 border-red-500/20 bg-red-500/10",
  },
  "vijay-sales": {
    id: "vijay-sales",
    name: "Vijay Sales",
    countryCode: "IN",
    currency: "INR",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "merchant_feed",
    dataSource: "Vijay Sales Electronics Partner Feed",
    affiliateSupported: true,
    iconColorClass: "text-emerald-400 border-emerald-500/20 bg-emerald-500/10",
  },
  "lenovo-store": {
    id: "lenovo-store",
    name: "Lenovo Official Store",
    countryCode: "IN",
    currency: "INR",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "api",
    dataSource: "Lenovo PSREF & Official Brand Store API",
    affiliateSupported: false,
    iconColorClass: "text-indigo-400 border-indigo-500/20 bg-indigo-500/10",
  },
  "hp-store": {
    id: "hp-store",
    name: "HP Official Store",
    countryCode: "IN",
    currency: "INR",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "api",
    dataSource: "HP Online Store Direct API",
    affiliateSupported: false,
    iconColorClass: "text-sky-400 border-sky-500/20 bg-sky-500/10",
  },
  "asus-store": {
    id: "asus-store",
    name: "ASUS Official Store",
    countryCode: "IN",
    currency: "INR",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "api",
    dataSource: "ASUS E-Store Partner API",
    affiliateSupported: false,
    iconColorClass: "text-cyan-400 border-cyan-500/20 bg-cyan-500/10",
  },
  "apple-store": {
    id: "apple-store",
    name: "Apple Store India",
    countryCode: "IN",
    currency: "INR",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "merchant_feed",
    dataSource: "Apple India Online Store Feed",
    affiliateSupported: false,
    iconColorClass: "text-surface-200 border-surface-600 bg-surface-800/40",
  },
  "dell-store": {
    id: "dell-store",
    name: "Dell Official Store",
    countryCode: "IN",
    currency: "INR",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "api",
    dataSource: "Dell India Store Direct API",
    affiliateSupported: false,
    iconColorClass: "text-blue-300 border-blue-400/20 bg-blue-400/10",
  },
  "bestbuy-us": {
    id: "bestbuy-us",
    name: "Best Buy US",
    countryCode: "US",
    currency: "USD",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "api",
    dataSource: "Best Buy Developer API",
    affiliateSupported: true,
    iconColorClass: "text-yellow-400 border-yellow-500/20 bg-yellow-500/10",
  },
  "amazon-us": {
    id: "amazon-us",
    name: "Amazon US",
    countryCode: "US",
    currency: "USD",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "api",
    dataSource: "Amazon Associates US API",
    affiliateSupported: true,
    iconColorClass: "text-amber-400 border-amber-500/20 bg-amber-500/10",
  },
  "currys-uk": {
    id: "currys-uk",
    name: "Currys UK",
    countryCode: "UK",
    currency: "GBP",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "affiliate_feed",
    dataSource: "Currys UK Partner Network",
    affiliateSupported: true,
    iconColorClass: "text-purple-400 border-purple-500/20 bg-purple-500/10",
  },
  "amazon-uk": {
    id: "amazon-uk",
    name: "Amazon UK",
    countryCode: "UK",
    currency: "GBP",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "api",
    dataSource: "Amazon Associates UK API",
    affiliateSupported: true,
    iconColorClass: "text-amber-400 border-amber-500/20 bg-amber-500/10",
  },
  "amazon-de": {
    id: "amazon-de",
    name: "Amazon Europe",
    countryCode: "EU",
    currency: "EUR",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "api",
    dataSource: "Amazon Associates EU API",
    affiliateSupported: true,
    iconColorClass: "text-amber-400 border-amber-500/20 bg-amber-500/10",
  },
  ebay: {
    id: "ebay",
    name: "eBay",
    countryCode: "US",
    currency: "USD",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "api",
    dataSource: "eBay Browse API (Developer Account Pending)",
    affiliateSupported: true,
    iconColorClass: "text-blue-400 border-blue-500/20 bg-blue-500/10",
  },
  quickcommerce: {
    id: "quickcommerce",
    name: "QuickCommerce Network",
    countryCode: "IN",
    currency: "INR",
    enabled: true,
    connectionStatus: "not_connected",
    dataSourceType: "api",
    dataSource: "QuickCommerce Multi-Platform Marketplace API",
    affiliateSupported: true,
    iconColorClass: "text-emerald-400 border-emerald-500/20 bg-emerald-500/10",
  },
};

/**
 * Retrieves metadata for a specific retailer by ID
 */
export function getRetailerInfo(id: RetailerId): RetailerInfo {
  return (
    RETAILER_REGISTRY[id] || {
      id,
      name: id,
      countryCode: "IN",
      currency: "INR",
      enabled: true,
      connectionStatus: "not_connected",
      dataSourceType: "manual_verified",
      dataSource: "Generic Partner Feed",
      affiliateSupported: false,
      iconColorClass: "text-brand-400 border-brand-500/20 bg-brand-500/10",
    }
  );
}

/**
 * Returns all registered retailers for a given country code
 */
export function getRetailersForCountry(countryCode: string = "IN"): RetailerInfo[] {
  return Object.values(RETAILER_REGISTRY).filter((r) => r.countryCode === countryCode && r.enabled);
}
